#!/usr/bin/env python3
"""PreToolUse hook: structural validation for deep references.

Fires before a Write or Edit against any deep reference under
`corpus.commons/{any-corpus}/references/*-deep.md` or
`corpus.local/{any-corpus}/references/*-deep.md`. Performs the
deterministic, false-positive-free checks that the 9-pass protocol
requires every deep reference to satisfy. The Pass I source-only audit
runs at the model level and catches drift from the source; this hook runs
at write time and catches drift from the *protocol's structural contract*.

Why PreToolUse not PostToolUse: PostToolUse would let a malformed file land
before the check fires, leaving a broken file on disk if the next step
fails. PreToolUse predicts the post-write state from the tool input and
blocks the call entirely if validation fails, so the file on disk never
gets corrupted.

Reads JSON from stdin per the Claude Code hook spec; uses exit codes:
  0 → check passed, write proceeds.
  2 → check failed, write is blocked, stderr surfaces to the model so the
       next turn can repair the content. Use exit 2 (not 1) because the
       model only sees stderr on exit 2.

The contract checked here:
  1. HTML-comment generation header on line 1 with `Generated by:` and
     `Source-grounded` markers (Pass A).
  2. `**Source:**`, `**Scope:**`, `**Structure:**`, `**Citation style:**`,
     `**Coverage:**` block present near the head (Pass A → E).
  3. `**Scope:**` value is one of the five permitted ranks.
  4. Every blockquote (`>` lines) is followed within 5 lines by a citation
     (parenthetical or page reference).
  5. Evidence-class markers are well-formed where present: `[V]`, `[AP]`,
     `[AR]`, `[AE]`, `[BT]` only.
  6. No half-finished pass artefact text (`TODO:`, `XXX:`, `[citation
     pending]`, `(pending)`).

What this hook does NOT do:
  - Judge whether claims are actually supported by the source (that's
    Pass I, model-level audit).
  - Count claim-line coverage (that's `scripts/audit-deep-ref.py`,
    heuristic, runs on demand).
  - Enforce the canonical section structure of the deep ref template
    (different sources legitimately need different sections).

Run standalone against an existing file:
    python3 .claude/hooks/validate-deep-ref.py --file corpus.commons/demo/references/foo-deep.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PERMITTED_SCOPES = {"open", "open-nc", "copyrighted", "confidential", "personal"}
PERMITTED_MARKERS = {"[V]", "[AP]", "[AR]", "[AE]", "[BT]"}
MARKER_PATTERN = re.compile(r"\[([A-Z]{1,3})\](?=[\s,.;:)\]]|$)")
CITATION_TAIL_PATTERN = re.compile(
    r"\((?:Ch\s+\d+|p\.\s*\d+|pp\.\s*\d+|[A-Z][a-z]+\s+\d{4}|\"[^\"]+\"|§)",
)
PENDING_PATTERNS = [
    re.compile(r"\bTODO\b"),
    re.compile(r"\bXXX\b"),
    re.compile(r"\bFIXME\b"),
    re.compile(r"\[citation\s+pending\]", re.IGNORECASE),
    re.compile(r"\[citation\s+needed\]", re.IGNORECASE),
    re.compile(r"\(pending\)", re.IGNORECASE),
]


def check_text(text: str) -> list[str]:
    """Return a list of violation messages against the deep-ref contract."""
    violations: list[str] = []

    if not text.strip():
        return ["file is empty"]

    lines = text.split("\n")

    # 1. Generation header on line 1.
    header = lines[0] if lines else ""
    if not header.startswith("<!--") or "Generated by" not in header or "Source-grounded" not in header:
        violations.append(
            "line 1 must be the Pass A generation header: "
            "`<!-- Generated by: ... | ... | Source-grounded | ... -->`"
        )

    # 2. Required frontmatter markers near the head.
    head = "\n".join(lines[:60])
    required_blocks = ["Source", "Scope", "Structure", "Citation style", "Coverage"]
    for marker in required_blocks:
        if not re.search(rf"^\*\*{re.escape(marker)}:\*\*", head, re.MULTILINE):
            violations.append(f"missing required block `**{marker}:**` in head of file")

    # 3. Scope value is permitted.
    scope_match = re.search(r"^\*\*Scope:\*\*\s*(\S+)", head, re.MULTILINE)
    if scope_match:
        scope_value = scope_match.group(1).strip().rstrip(".,")
        if scope_value not in PERMITTED_SCOPES:
            violations.append(
                f"**Scope:** value `{scope_value}` is not one of "
                f"{sorted(PERMITTED_SCOPES)}"
            )

    # 4. Every blockquote is followed within 5 lines by a citation.
    for idx, line in enumerate(lines):
        if not line.startswith("> "):
            continue
        end_idx = idx
        while end_idx + 1 < len(lines) and lines[end_idx + 1].startswith(">"):
            end_idx += 1
        window = "\n".join(lines[end_idx : min(end_idx + 6, len(lines))])
        if not CITATION_TAIL_PATTERN.search(window):
            violations.append(
                f"line {idx + 1}: blockquote not followed by a citation "
                f"within 5 lines (expected `(Ch N, ...)` or `(p. N)` style)"
            )
            break  # one report per file is enough

    # 5. Evidence-class markers are well-formed.
    seen_bad = set()
    for m in MARKER_PATTERN.finditer(text):
        token = f"[{m.group(1)}]"
        if token not in PERMITTED_MARKERS and token not in seen_bad:
            seen_bad.add(token)
            violations.append(
                f"unknown evidence-class marker `{token}` "
                f"(permitted: {sorted(PERMITTED_MARKERS)})"
            )

    # 6. No half-finished pass artefacts.
    for pat in PENDING_PATTERNS:
        m = pat.search(text)
        if m:
            line_no = text[: m.start()].count("\n") + 1
            violations.append(
                f"line {line_no}: half-finished marker `{m.group(0)}`; "
                f"resolve before commit"
            )
            break

    return violations


def predict_write_result(tool_name: str, tool_input: dict, file_path: Path) -> str | None:
    """Predict what the file contents will be after the tool call.

    Returns the predicted content, or None if we can't predict (caller
    should skip validation in that case).
    """
    if tool_name == "Write":
        return tool_input.get("content", "")

    if tool_name == "Edit":
        old_string = tool_input.get("old_string", "")
        new_string = tool_input.get("new_string", "")
        replace_all = tool_input.get("replace_all", False)
        try:
            current = file_path.read_text(encoding="utf-8") if file_path.exists() else ""
        except OSError:
            return None
        if replace_all:
            return current.replace(old_string, new_string)
        # Edit semantics: must be unique. If not unique we can't reliably
        # predict; fall back to None and let the tool surface its own error.
        if current.count(old_string) != 1:
            return None
        return current.replace(old_string, new_string, 1)

    return None


def _is_deep_ref_path(path: Path) -> bool:
    """True if path is a deep ref under any corpus root (commons or local).

    Matches `{...}/corpus.commons/{any-corpus}/references/{slug}-deep.md`
    and the same shape under `corpus.local/`. Forks that rename the corpus
    or add new corpora keep validation coverage automatically.
    """
    if not path.name.endswith("-deep.md"):
        return False
    parts = path.as_posix()
    for tier in ("corpus.commons", "corpus.local"):
        marker = f"/{tier}/"
        # Check both absolute paths (containing the marker) and repo-relative
        # paths (starting with the marker without the leading slash).
        if marker in parts or parts.startswith(f"{tier}/"):
            # Confirm it lands under .../{tier}/{corpus}/references/
            after = parts.split(marker, 1)[-1] if marker in parts else parts.split(f"{tier}/", 1)[-1]
            segments = after.split("/")
            if len(segments) >= 3 and segments[1] == "references":
                return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--file",
        type=Path,
        help="check a specific file on disk (standalone mode, bypasses stdin)",
    )
    args = parser.parse_args()

    if args.file:
        if not _is_deep_ref_path(args.file):
            print(f"Not a deep-ref path: {args.file}")
            return 0
        try:
            text = args.file.read_text(encoding="utf-8")
        except OSError as e:
            sys.stderr.write(f"Could not read {args.file}: {e}\n")
            return 2
        violations = check_text(text)
        if violations:
            sys.stderr.write(f"Deep-ref validation failed: {args.file}\n")
            for v in violations:
                sys.stderr.write(f"  - {v}\n")
            return 2
        print(f"OK: {args.file}")
        return 0

    # Hook mode: read JSON from stdin.
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0

    tool_name = payload.get("tool_name", "")
    tool_input = payload.get("tool_input", {})
    file_path_str = tool_input.get("file_path", "")
    if not file_path_str:
        return 0

    path = Path(file_path_str)
    if not _is_deep_ref_path(path):
        return 0

    predicted = predict_write_result(tool_name, tool_input, path)
    if predicted is None:
        # Either an unsupported tool or a non-unique Edit; let the tool
        # itself handle the error rather than blocking pre-emptively.
        return 0

    violations = check_text(predicted)
    if violations:
        sys.stderr.write(
            f"Deep-ref structural validation failed for {path.name}.\n"
            "The 9-pass protocol requires every deep reference to satisfy these checks:\n"
        )
        for v in violations:
            sys.stderr.write(f"  - {v}\n")
        sys.stderr.write(
            "\nFix the content and retry, or run "
            "`python3 .claude/hooks/validate-deep-ref.py --file <path>` standalone "
            "to validate an existing file.\n"
        )
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
