#!/usr/bin/env python3
"""Derived-tier provenance regression tests — the jocham class.

Locks in the behaviour of `scripts/check_derived_provenance.py`, the guard that
pre-push Check 9 depends on. The regression it exists to prevent is the jocham
incident: Pass I stripped content from a deep reference, but the light ref and
distillations derived from the *pre-audit* deep kept asserting it, and nothing
re-checked them. The provenance stamp closes that by recording the deep's hash
on each derived artefact; a later deep edit that is not followed by re-derivation
strands the derived tier, which the check must flag as STALE.

This is the test-file-vs-evalset distinction (Gulli, Ch 19) applied correctly:
an end-to-end check that a deep edit propagates, exercised against the real CLI
over a hermetic fixture corpus (a temp dir passed via --root), so it touches no
real corpus and needs no LLM.

Four properties, each a case that throws on failure:
  1. A correctly-derived, stamped tier reads clean (exit 0).
  2. jocham: editing the deep without re-deriving strands the tier → STALE, exit 1.
  3. Re-deriving and re-stamping restores clean (exit 0).
  4. An unstamped artefact only WARNS, never fails (exit 0) — the property that
     lets the gate be wired before adoption is broad. A regression here would
     silently turn the ratchet into a hard block.

No test framework, matching tests/lens-visibility.test.js: each case succeeds
silently or raises; the runner collects failures, prints a summary, exits non-zero.

Usage:
    python3 tests/derived-provenance.test.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CHECK = REPO_ROOT / "scripts" / "check_derived_provenance.py"

SLUG = "fixture-source"
TASK = "aar"
STAMP_RE_HINT = "derived-from-deep"


def assert_(cond: bool, msg: str) -> None:
    if not cond:
        raise AssertionError(msg)


def stale_lines(out: str) -> list[str]:
    """Per-artefact STALE report lines, not the '... K STALE.' summary tail."""
    return [ln for ln in out.splitlines() if ln.startswith("STALE")]


def run_check(root: Path, *extra: str) -> tuple[int, str]:
    """Invoke the real CLI against a fixture root; return (exit_code, output)."""
    proc = subprocess.run(
        [sys.executable, str(CHECK), "--root", str(root), *extra],
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout + proc.stderr


def build_fixture(root: Path, *, claim: str) -> None:
    """A minimal corpus: one deep, one light ref, one distillation.

    The deep's validity is irrelevant to the provenance check (it only hashes
    the deep and locates derived artefacts by slug), so the bodies are minimal.
    `claim` is a sentinel line written into the deep and both derived artefacts,
    standing in for a load-bearing claim that Pass I might later strip.
    """
    (root / "references").mkdir(parents=True, exist_ok=True)
    (root / "distillations" / TASK).mkdir(parents=True, exist_ok=True)

    deep = root / "references" / f"{SLUG}-deep.md"
    deep.write_text(
        f"<!-- Generated by: test-fixture -->\n# Deep: {SLUG}\n\n{claim}\n",
        encoding="utf-8",
    )
    (root / "references" / f"{SLUG}.md").write_text(
        f"<!-- Generated by: test-fixture -->\n# Light: {SLUG}\n\n{claim}\n",
        encoding="utf-8",
    )
    (root / "distillations" / TASK / f"{SLUG}-{TASK}.md").write_text(
        f"<!-- Generated by: test-fixture -->\n# {SLUG} ({TASK})\n\n{claim}\n",
        encoding="utf-8",
    )


def strip_claim_from_deep(root: Path, claim: str) -> None:
    """Simulate Pass I removing a claim from the deep (bytes change → hash moves)."""
    deep = root / "references" / f"{SLUG}-deep.md"
    text = deep.read_text(encoding="utf-8").replace(claim + "\n", "")
    assert_(claim not in text, "claim should be gone from the deep after strip")
    deep.write_text(text, encoding="utf-8")


def rederive(root: Path, claim: str) -> None:
    """Simulate correct re-derivation: remove the stripped claim from the tier."""
    for p in (
        root / "references" / f"{SLUG}.md",
        root / "distillations" / TASK / f"{SLUG}-{TASK}.md",
    ):
        text = p.read_text(encoding="utf-8").replace(claim + "\n", "")
        p.write_text(text, encoding="utf-8")


# ─── cases ────────────────────────────────────────────────────────────────────


def case_clean_state_passes(root: Path) -> None:
    build_fixture(root, claim="CLAIM-X supported by the deep.")
    rc, _ = run_check(root, "--stamp")
    assert_(rc == 0, "stamping a fixture should succeed")

    # Both derived artefacts now carry a matching stamp.
    light = (root / "references" / f"{SLUG}.md").read_text(encoding="utf-8")
    assert_(STAMP_RE_HINT in light, "light ref should be stamped after --stamp")

    rc, out = run_check(root)
    assert_(rc == 0, f"clean stamped tier should pass (exit 0); got {rc}\n{out}")
    assert_(not stale_lines(out), f"clean tier should report no STALE artefacts\n{out}")
    assert_("2 current" in out, f"expected 2 current artefacts\n{out}")


def case_jocham_deep_edit_strands_tier(root: Path) -> None:
    """THE regression: deep changes, tier is not re-derived → must fail STALE."""
    claim = "CLAIM-X supported by the deep."
    build_fixture(root, claim=claim)
    run_check(root, "--stamp")  # correctly-derived starting point

    strip_claim_from_deep(root, claim)  # Pass I edits the deep, tier untouched

    rc, out = run_check(root)
    assert_(rc == 1, f"stranded tier must fail with exit 1 (STALE); got {rc}\n{out}")
    assert_(
        len(stale_lines(out)) == 2,
        f"both stranded derived artefacts should read STALE\n{out}",
    )
    # The stranded artefacts still assert the stripped claim — the exact jocham harm.
    light = (root / "references" / f"{SLUG}.md").read_text(encoding="utf-8")
    assert_(claim in light, "fixture precondition: the tier still asserts the claim")


def case_rederive_and_restamp_restores_clean(root: Path) -> None:
    claim = "CLAIM-X supported by the deep."
    build_fixture(root, claim=claim)
    run_check(root, "--stamp")
    strip_claim_from_deep(root, claim)
    assert_(run_check(root)[0] == 1, "precondition: should be STALE before the fix")

    rederive(root, claim)  # remove the claim from the tier too
    run_check(root, "--stamp")  # re-stamp against the new deep hash

    rc, out = run_check(root)
    assert_(rc == 0, f"re-derived + re-stamped tier should pass; got {rc}\n{out}")
    assert_(not stale_lines(out), f"no STALE after correct fix\n{out}")


def case_unstamped_only_warns(root: Path) -> None:
    """The property that made wiring the gate safe: unstamped warns, never fails."""
    build_fixture(root, claim="CLAIM-X supported by the deep.")
    # Note: no --stamp. Artefacts are unstamped.
    rc, out = run_check(root)
    assert_(rc == 0, f"unstamped tier must NOT fail the gate; got exit {rc}\n{out}")
    assert_("unstamped" in out, f"unstamped artefacts should be reported as warn\n{out}")
    assert_(not stale_lines(out), f"unstamped is not STALE\n{out}")


CASES = [
    case_clean_state_passes,
    case_jocham_deep_edit_strands_tier,
    case_rederive_and_restamp_restores_clean,
    case_unstamped_only_warns,
]


def main() -> int:
    failures: list[str] = []
    for case in CASES:
        tmp = Path(tempfile.mkdtemp(prefix="prov-test-"))
        try:
            case(tmp)
            print(f"  ok   {case.__name__}")
        except Exception as e:  # noqa: BLE001 — test runner reports any failure
            failures.append(f"{case.__name__}: {e}")
            print(f"  FAIL {case.__name__}: {e}")
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    print()
    if failures:
        print(f"derived-provenance: {len(failures)} of {len(CASES)} cases FAILED")
        return 1
    print(f"derived-provenance: all {len(CASES)} cases passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
