#!/usr/bin/env python3
"""Runtime-agnostic core of the deep-reference structural validator.

This module holds the deterministic, false-positive-free checks that the
9-pass protocol requires every deep reference to satisfy. It knows nothing
about any coding agent's tool-call format: it takes strings and paths and
returns violation messages. Runtime adapters (Claude's PreToolUse hook, a
Codex hook, CI, the git pre-push audit) import from here so the enforcement
logic lives in exactly one place.

The split is deliberate. `check_text()` and `is_deep_ref_path()` are the
durable contract; a vendor adapter only needs to (a) recognise which of its
tool calls will write a deep-ref path and (b) predict the post-write content,
then hand that string to `check_text()`. See `.claude/hooks/validate-deep-ref.py`
for the reference adapter.

The contract checked here:
  1. HTML-comment generation header on line 1 with `Generated by:` and
     `Source-grounded` markers (Pass A).
  2. `**Source:**`, `**Scope:**`, `**Structure:**`, `**Citation style:**`,
     `**Coverage:**` block present near the head (Pass A → E).
  3. `**Scope:**` value is one of the five permitted ranks.
  4. Every blockquote (`>` lines) is followed within 5 lines by a citation
     (parenthetical or page reference).
  5. Evidence-class markers are well-formed where present: `[V]`, `[AP]`,
     `[AR]`, `[AE]`, `[BT]` only.
  6. No half-finished pass artefact text (`TODO:`, `XXX:`, `[citation
     pending]`, `(pending)`).

What this module does NOT do:
  - Judge whether claims are actually supported by the source (that's
    Pass I, model-level audit).
  - Count claim-line coverage (that's `scripts/audit-deep-ref.py`,
    heuristic, runs on demand).
  - Enforce the canonical section structure of the deep ref template
    (different sources legitimately need different sections).

Run standalone against an existing file (runtime-neutral):
    python3 scripts/validate/deep_ref_core.py --file corpus.commons/demo/references/foo-deep.md
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PERMITTED_SCOPES = {"open", "open-nc", "copyrighted", "confidential", "personal"}
PERMITTED_MARKERS = {"[V]", "[AP]", "[AR]", "[AE]", "[BT]"}
MARKER_PATTERN = re.compile(r"\[([A-Z]{1,3})\](?=[\s,.;:)\]]|$)")
CITATION_TAIL_PATTERN = re.compile(
    r"\((?:Ch\s+\d+|p\.\s*\d+|pp\.\s*\d+|[A-Z][a-z]+\s+\d{4}|\"[^\"]+\"|§)",
)
PENDING_PATTERNS = [
    re.compile(r"\bTODO\b"),
    re.compile(r"\bXXX\b"),
    re.compile(r"\bFIXME\b"),
    re.compile(r"\[citation\s+pending\]", re.IGNORECASE),
    re.compile(r"\[citation\s+needed\]", re.IGNORECASE),
    re.compile(r"\(pending\)", re.IGNORECASE),
]


def check_text(text: str) -> list[str]:
    """Return a list of violation messages against the deep-ref contract."""
    violations: list[str] = []

    if not text.strip():
        return ["file is empty"]

    lines = text.split("\n")

    # 1. Generation header on line 1.
    header = lines[0] if lines else ""
    if not header.startswith("<!--") or "Generated by" not in header or "Source-grounded" not in header:
        violations.append(
            "line 1 must be the Pass A generation header: "
            "`<!-- Generated by: ... | ... | Source-grounded | ... -->`"
        )

    # 2. Required frontmatter markers near the head.
    head = "\n".join(lines[:60])
    required_blocks = ["Source", "Scope", "Structure", "Citation style", "Coverage"]
    for marker in required_blocks:
        if not re.search(rf"^\*\*{re.escape(marker)}:\*\*", head, re.MULTILINE):
            violations.append(f"missing required block `**{marker}:**` in head of file")

    # 3. Scope value is permitted.
    scope_match = re.search(r"^\*\*Scope:\*\*\s*(\S+)", head, re.MULTILINE)
    if scope_match:
        scope_value = scope_match.group(1).strip().rstrip(".,")
        if scope_value not in PERMITTED_SCOPES:
            violations.append(
                f"**Scope:** value `{scope_value}` is not one of "
                f"{sorted(PERMITTED_SCOPES)}"
            )

    # 4. Every blockquote is followed within 5 lines by a citation.
    for idx, line in enumerate(lines):
        if not line.startswith("> "):
            continue
        end_idx = idx
        while end_idx + 1 < len(lines) and lines[end_idx + 1].startswith(">"):
            end_idx += 1
        window = "\n".join(lines[end_idx : min(end_idx + 6, len(lines))])
        if not CITATION_TAIL_PATTERN.search(window):
            violations.append(
                f"line {idx + 1}: blockquote not followed by a citation "
                f"within 5 lines (expected `(Ch N, ...)` or `(p. N)` style)"
            )
            break  # one report per file is enough

    # 5. Evidence-class markers are well-formed.
    seen_bad = set()
    for m in MARKER_PATTERN.finditer(text):
        token = f"[{m.group(1)}]"
        if token not in PERMITTED_MARKERS and token not in seen_bad:
            seen_bad.add(token)
            violations.append(
                f"unknown evidence-class marker `{token}` "
                f"(permitted: {sorted(PERMITTED_MARKERS)})"
            )

    # 6. No half-finished pass artefacts.
    for pat in PENDING_PATTERNS:
        m = pat.search(text)
        if m:
            line_no = text[: m.start()].count("\n") + 1
            violations.append(
                f"line {line_no}: half-finished marker `{m.group(0)}`; "
                f"resolve before commit"
            )
            break

    return violations


def is_deep_ref_path(path: Path) -> bool:
    """True if path is a deep ref under any corpus root (commons or local).

    Matches `{...}/corpus.commons/{any-corpus}/references/{slug}-deep.md`
    and the same shape under `corpus.local/`. Forks that rename the corpus
    or add new corpora keep validation coverage automatically.
    """
    if not path.name.endswith("-deep.md"):
        return False
    parts = path.as_posix()
    for tier in ("corpus.commons", "corpus.local"):
        marker = f"/{tier}/"
        # Check both absolute paths (containing the marker) and repo-relative
        # paths (starting with the marker without the leading slash).
        if marker in parts or parts.startswith(f"{tier}/"):
            # Confirm it lands under .../{tier}/{corpus}/references/
            after = parts.split(marker, 1)[-1] if marker in parts else parts.split(f"{tier}/", 1)[-1]
            segments = after.split("/")
            if len(segments) >= 3 and segments[1] == "references":
                return True
    return False


def check_file(path: Path) -> tuple[int, list[str]]:
    """Validate a file on disk. Runtime-neutral.

    Returns `(exit_code, messages)`:
      (0, [])            → not a deep-ref path; nothing to check.
      (0, [])            → deep-ref path, all checks pass.
      (2, [violations])  → deep-ref path, one or more violations.
      (2, [read-error])  → path could not be read.
    """
    if not is_deep_ref_path(path):
        return 0, []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        return 2, [f"could not read {path}: {e}"]
    violations = check_text(text)
    return (2 if violations else 0), violations


def _main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--file",
        type=Path,
        required=True,
        help="check a specific file on disk (runtime-neutral standalone mode)",
    )
    args = parser.parse_args()

    if not is_deep_ref_path(args.file):
        print(f"Not a deep-ref path: {args.file}")
        return 0
    exit_code, messages = check_file(args.file)
    if exit_code != 0:
        sys.stderr.write(f"Deep-ref validation failed: {args.file}\n")
        for m in messages:
            sys.stderr.write(f"  - {m}\n")
        return exit_code
    print(f"OK: {args.file}")
    return 0


if __name__ == "__main__":
    sys.exit(_main())
